//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "group")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recipient_group_j::Entity")]
    RecipientGroupJ,
}

impl Related<super::recipient_group_j::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecipientGroupJ.def()
    }
}

impl Related<super::recipient::Entity> for Entity {
    fn to() -> RelationDef {
        super::recipient_group_j::Relation::Recipient.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recipient_group_j::Relation::Group.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
