//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::contact::Entity as Contact;
pub use super::group::Entity as Group;
pub use super::recipient::Entity as Recipient;
pub use super::recipient_group_j::Entity as RecipientGroupJ;
pub use super::subscription::Entity as Subscription;
