[workspace]
resolver = "2"
members = [
    "notifico-core",
    "transports/notifico-smtp",
    "transports/notifico-telegram",
    "transports/notifico-whatsapp",
    "transports/notifico-smpp",
    "notifico-template",
    "notifico-worker",
]

[workspace.dependencies]
reqwest = { version = "0.12.8", default-features = false, features = ["json", "default-tls", "charset"] }
axum = "0.8.0-alpha.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
