[package]
name = "rule_engine"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"

[dependencies]
#lapin = "2.5.0"
tokio = { version = "1.40", features = ["full"] }
log = "0.4.22"
futures = "0.3.30"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
serde = { version = "1.0.210", features = ["derive"] }
#sea-orm = { version = "1.1.0-rc.1", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros"] }
uuid = { version = "1.10.0", features = ["serde"] }
serde_json = "1.0.128"
reqwest = { version = "0.12.7", features = ["json"] }
async-trait = "0.1.82"
url = "2.5.2"
figment = { version = "0.10.19", features = ["yaml", "env"] }
clap = { version = "4.5.17", features = ["derive", "color", "usage"] }
notifico-core = { path = "notifico-core" }
notifico-telegram = { path = "notifico-telegram" }
notifico-smtp = { path = "notifico-smtp" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace]
members = [".", "notifico-core", "notifico-smtp", "notifico-telegram"]
