[package]
name = "notifico"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"

[dependencies]
tokio = { version = "1.40", features = ["macros", "rt", "sync"] }
log = "0.4.22"
futures = "0.3.31"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
serde = { version = "1.0.210", features = ["derive"] }
uuid = { version = "1.11.0", features = ["serde", "v7"] }
serde_json = "1.0.130"
reqwest = { workspace = true }
async-trait = "0.1.83"
url = "2.5.2"
figment = { version = "0.10.19", features = ["yaml", "env"] }
clap = { version = "4.5.20", features = ["derive", "color", "usage"] }
actix = "0.13.5"
axum = { workspace = true }
jsonwebtoken = "9.3.0"
anyhow = "1.0.90"

notifico-core = { path = "notifico-core" }
notifico-telegram = { path = "transports/notifico-telegram" }
notifico-smtp = { path = "transports/notifico-smtp" }
notifico-whatsapp = { path = "transports/notifico-whatsapp" }
notifico-smpp = { path = "transports/notifico-smpp" }
notifico-template = { path = "notifico-template" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[workspace]
members = [
    "notifico-core",
    "transports/notifico-smtp",
    "transports/notifico-telegram",
    "transports/notifico-whatsapp",
    "transports/notifico-smpp",
    "notifico-template",
]

[workspace.dependencies]
reqwest = { version = "0.12.8", default-features = false, features = ["json", "default-tls", "charset"] }
axum = "0.8.0-alpha.1"
