templates = "/home/gamepad/notifico/templates"
pipelines = "pipelines.yml"
credentials = "credentials.toml"

[http]
bind = "[::]:3000"

[amqp]
#bind = "[::]:5432"
url = "amqp://guest:guest@127.0.0.1"
address = "notifico1"