events:
  - name: send_notification
pipelines:
  - channel: telegram
    events:
      - send_notification
    steps:
      - step: templates.load
        templates: [ "zerna.toml" ]
      - step: telegram.send
        credential: telegram_bot_1
  - channel: email
    events:
      - send_notification
    steps:
      - step: templates.load
        templates: [ "zerna.toml" ]
      - step: email.send
        credential: mailman_1
