[package]
name = "notifico-whatsapp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
uuid = { workspace = true }
serde_json = "1.0.133"
async-trait = "0.1.83"
reqwest = { workspace = true }
tracing = "0.1.41"
regex = "1.11.1"

notifico-core = { path = "../../notifico-core" }
