[package]
name = "notifico-attachment"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../notifico-core" }

serde = { version = "1.0.217", features = ["derive"] }
async-trait = "0.1.84"
tokio = { version = "1.43.0", features = ["fs", "sync"] }
mime_guess = "2.0.5"
