[package]
name = "notifico-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.84"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
uuid = { workspace = true }
tracing = "0.1.41"
tokio = "1.42.0"
axum = { workspace = true }
url = { workspace = true }
sea-orm = { workspace = true }
anyhow = "1.0.95"
utoipa = { workspace = true }
flume = "0.11.1"
thiserror = "2.0.9"
regex = "1.11.1"
serde_with = "3.12.0"
futures = "0.3.31"
multimap = "0.10.0"
