[package]
name = "notifico-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
uuid = { version = "1.11.0", features = ["serde", "v7"] }
tracing = "0.1.40"
tokio = "1.41.1"
jsonwebtoken = "9.3.0"
axum = { workspace = true }
url = { version = "2.5.3", features = ["serde"] }
sea-orm = { workspace = true }
anyhow = "1.0.93"
utoipa = { version = "5", features = ["uuid"] }
