[package]
name = "notifico-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
uuid = { workspace = true }
tracing = "0.1.41"
tokio = "1.42.0"
axum = { workspace = true }
url = { workspace = true }
sea-orm = { workspace = true }
anyhow = "1.0.94"
utoipa = { version = "5", features = ["uuid"] }
flume = "0.11.1"
