[package]
name = "notificox"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../notifico-core" }
notifico-template = { path = "../notifico-template" }
# Transports
notifico-telegram = { path = "../transports/notifico-telegram" }
notifico-smtp = { path = "../transports/notifico-smtp" }
notifico-whatsapp = { path = "../transports/notifico-whatsapp" }
notifico-smpp = { path = "../transports/notifico-smpp" }
notifico-slack = { path = "../transports/notifico-slack" }
notifico-pushover = { path = "../transports/notifico-pushover" }
notifico-gotify = { path = "../transports/notifico-gotify" }
# Other deps
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["rt"] }
clap = { workspace = true }
json5 = "0.4.1"
flume = "0.11.1"
dotenvy = "0.15.7"
uuid = { workspace = true }
log = "0.4.22"
env_logger = "0.11.5"
url = "2.5.4"
anyhow = "1.0.94"
regex = "1.11.1"
