//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::event::Entity as Event;
pub use super::pipeline::Entity as Pipeline;
pub use super::pipeline_event_j::Entity as PipelineEventJ;
