[package]
name = "notifico-pushover"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../../notifico-core" }
notifico-attachment = { path = "../../notifico-attachment" }

reqwest = { workspace = true }
async-trait = "0.1.84"
serde = "1.0.217"
url = "2.5.4"
