[package]
name = "notifico-telegram"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tracing = "0.1.41"
uuid = { workspace = true }
teloxide = "0.13.0"

notifico-core = { path = "../../notifico-core" }
