version: "3"
services:
  ingest:
    image: notificohq/notifico-ingest
    environment: &environment
      NOTIFICO_AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      NOTIFICO_SECRET_KEY: weak-secret-key
      NOTIFICO_DB: sqlite:///var/lib/notifico/db.sqlite3
      NOTIFICO_USERAPI_URL: http://localhost:9000/

      NOTIFICO_CRED_MAIL1: smtp:YOUR_SMTP_USERNAME:YOUR_SMTP_PASSWORD@YOUR_SMTP_SERVER:587?tls=true
      NOTIFICO_CRED_SMS1: smpp:YOUR_SMPP_SYSTEM_ID:YOUR_SMPP_PASSWORD@YOUR_SMPP_SERVER:2775
      NOTIFICO_CRED_TELEGRAM1: telegram:YOUR_TELEGRAM_TOKEN
      NOTIFICO_CRED_WHATSAPP1: waba:PHONE_ID:YOUR_WHATSAPP_TOKEN
      NOTIFICO_CRED_SLACK1: slack:xoxb-YOUR_SLACK_BOT_TOKEN
    ports:
      - "8001:8000"
    restart: unless-stopped
      
  userapi:
    image: notificohq/notifico-userapi
    environment: *environment  # Same environment
    ports:
      - "9000:8000"
    volumes:
      - data:/var/lib/notifico
    restart: unless-stopped

  web:
    image: notificohq/notifico-web
    environment: *environment  # Same environment
    ports:
      - "8000:8000"
    volumes:
      - data:/var/lib/notifico
    restart: unless-stopped

  worker:
    image: notificohq/notifico-worker
    environment: *environment  # Same environment
    volumes:
      - data:/var/lib/notifico
    restart: unless-stopped

  # Other services
  rabbitmq:
    image: rabbitmq:4.0
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      
volumes:
  data:
  rabbitmq:
