//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod contact;
pub mod event;
pub mod group;
pub mod group_membership;
pub mod pipeline;
pub mod pipeline_event_j;
pub mod project;
pub mod recipient;
pub mod subscription;
