//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::contact::Entity as Contact;
pub use super::event::Entity as Event;
pub use super::group::Entity as Group;
pub use super::pipeline::Entity as Pipeline;
pub use super::pipeline_event_j::Entity as PipelineEventJ;
pub use super::project::Entity as Project;
pub use super::recipient::Entity as Recipient;
pub use super::recipient_group_j::Entity as RecipientGroupJ;
pub use super::subscription::Entity as Subscription;
