[package]
name = "notifico-gotify"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../../notifico-core" }
reqwest = { workspace = true }
url = { workspace = true }
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
async-trait = "0.1.84"
