name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "notifico-worker"
          - "notifico-apiserver"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build images
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            notificohq/${{ matrix.image }}:latest
          context: .
          file: container/${{ matrix.image }}.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
