name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "notifico"
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Build images
      - uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            notificohq/${{ matrix.image }}:latest
            notificohq/${{ matrix.image }}:${{ github.ref_name }}
            ghcr.io/notificohq/${{ matrix.image }}:latest
            ghcr.io/notificohq/${{ matrix.image }}:${{ github.ref_name }}
          context: .
          file: container/${{ matrix.image }}.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
