[package]
name = "notifico-template"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../notifico-core" }
minijinja = { version = "2.3.1", default-features = false, features = ["builtins", "unicode", "serde", "debug", "urlencode", "speedups"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.130"
async-trait = "0.1.83"
tokio = { version = "1.40.0", features = ["fs"] }
tracing = "0.1.40"
