[package]
name = "notifico-template"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../notifico-core" }
minijinja = { version = "2.5.0", default-features = false, features = ["builtins", "unicode", "serde", "debug", "urlencode", "speedups"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
async-trait = "0.1.83"
tokio = { version = "1.41.1", features = ["fs"] }
tracing = "0.1.41"
toml = "0.8.19"
notifico-template-migration = { path = "migration" }
sea-orm = { workspace = true }
uuid = { workspace = true }
anyhow = "1.0.93"
thiserror = "2.0.3"
