[package]
name = "notifico-slack"
version = "0.1.0"
edition = "2021"

[dependencies]
notifico-core = { path = "../../notifico-core" }
reqwest = { workspace = true }
serde = "1.0.215"
async-trait = "0.1.83"
serde_json = "1.0.133"
thiserror = "2.0.4"
